config/routes.rb
KaigoApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
# encoding: utf-8
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'サインインに失敗 きちんと入力しましたか?'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end


  def index_sisetsu
    @users = User.find_by(:shubetu => 'riyousha')
  end


  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end


  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "ユーザー登録完了!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました。"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:shubetu, :name, :email, 
                                   :password, :password_confirmation)
    end

    # Before actions
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "サインインの必要があります"
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 与えられたユーザーのGravatar (http://gravatar.com/) を返す。
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">

<% case yield(:title) %>
 <%when "About" then%>
  概要
 <%when "Help" then%>
  質問
 <%when "" then%>
  トップ
 <%when "Sign up" then%>
  登録
 <%when "Sign in" then%>
  ログイン
 <%when "All users" then%>
  全ユーザー
 <%else%>
  ユーザー : <%= @user.name %>
<%end%>

<p><%= yield(:title) %></p>
<li><%= link_to "ヘルプ",  help_path %></li>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
	
          <% if signed_in? %>

	    <%case @current_user.shubetu%>
	      <%when "riyousha" then%>
  	        <h5>ようこそ <%= @current_user.name%> さん</h5>
	      <%when "care_manager" then%>
	        <h3>ようこそ ケアマネ さん</h3>
	      <%when "sisetu" then%>
	        <h3>ようこそ 施設 さん</h3>
	      <%else%>
	        <h3>ようこそ ゲスト さん</h3>
	    <%end%>

          <% else %>
            <h3>ようこそ ゲスト さん</h3>
          <% end %>

          <li><%= link_to "トップ",         root_path, id: "menu" %></li>
          <li><%= link_to "サイト概要",     about_path, id: "menu" %></li>
          <li><%= link_to "全ユーザー一覧", users_path , id: "menu" %></li>
          <li><%= link_to "ケアマネ一覧",      '#', id: "menu" %></li>

          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
                ユーザー設定 <b class="caret" ></b>
              </a>
              <ul class="dropdown-menu">

	        <%case @current_user.shubetu%>
	          <%when "riyousha" then%>
                    <li><%= link_to "プロフィール", current_user %></li>
                    <li><%= link_to "設定変更", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "サインアウト", signout_path, method: "delete" %>
                    </li>

                  <%when "care_manager" then%>
                    <li><%= link_to "プロフィール", current_user %></li>
                    <li><%= link_to "設定変更", edit_user_path(current_user) %></li>
                    <li><%= link_to "コメント投稿", "#"    %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "サインアウト", signout_path, method: "delete" %>
                    </li>

                  <%when "sisetu" then%>
                    <li><%= link_to "プロフィール", current_user %></li>
                    <li><%= link_to "設定変更", edit_user_path(current_user) %></li>
                    <li><%= ilnk_to "施設設定", "#"    %></li>
                    <li><%= link_to "募集案内", "#"    %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "サインアウト", signout_path, method: "delete" %>
                    </li>
                <%end%>

              </ul>
            </li>
          <% else %>
            <li><%= link_to "サインイン", signin_path, id: "menu" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>    
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>

  このサイトについてのページです。
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>

<p>
ヘルプのページです。
質問を受け付けます。
</p>

app/views/static_pages/home.html.erb
<h4>介護情報</h4>

<div class="center hero-unit">
  <h1>Kaigo App </h1>

  <h2>
    ここに情報を記載します。
  </h2>

  <h4>
    表の形式で表示する
  </h4>

</div>

<%= link_to "サインアップ", signup_path, class: "btn btn-large btn-primary" %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>ユーザー情報更新</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :shubetu, "種別" %>
      <%= f.select :shubetu, [["利用者", "riyousha"],
                    ["ケアマネージャー", "care_manager"],["施設", "sisetu"] ] %>

      <%= f.label :お名前 %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "更新します", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">画像の変更</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>ユーザー一覧</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :shubetu, "種別" %>
      <%= f.select :shubetu, [["利用者", "riyousha"],
                    ["ケアマネージャー", "care_manager"],["施設", "sisetu"] ] %>

      <%= f.label :name, "お名前" %>
      <%= f.text_field :name %>

      <%= f.label :email, "e-mail" %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "登録します", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>

	種別:<br>
	<%case @user.shubetu%>
	 <%when "riyousha" then%>
  	   利用者 <br>
	 <%when "care_manager" then%>
	   ケアマネ <br>
	 <%when "sisetu" then%>
	   施設 <br>
	<%end%>

	お名前:<br>
        <%= @user.name %><br>
	email :<br>
	<%= @user.email %><br>

        <%= link_to "About", about_path, class: "btn btn-large btn-primary" %>

      </h1>
    </section>
  </aside>
</div>